{
  "uid" : "914f010aebaf6515",
  "name" : "test_new_article_from_file",
  "fullName" : "test_conduit.test_case.TestConduit#test_new_article_from_file",
  "historyId" : "63b6b93441597676a773345a4b4e8dbe",
  "time" : {
    "start" : 1628457023067,
    "stop" : 1628457033197,
    "duration" : 10130
  },
  "status" : "broken",
  "statusMessage" : "IndexError: list index out of range",
  "statusTrace" : "self = <test_case.TestConduit object at 0x7f436bbcc6d0>\n\n    def test_new_article_from_file(self):\n        # belépés\n        self.test_login()\n        file = open('article_titles.txt', 'r')\n        list = file.read().splitlines() # \\n miatt soronként vágjuk\n        for x in range(5):  # 5 articole létrehozása, az első négy sor lesz egy article adatai...\n            href = self.browser.find_element_by_partial_link_text('New Article')\n            href.click()\n            time.sleep(1)\n            title_input = self.browser.find_element_by_xpath('//input[@placeholder=\"Article Title\"][@type=\"text\"]')\n>           title = list[1+4*x]\nE           IndexError: list index out of range\n\ntest_conduit/test_case.py:177: IndexError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "IndexError: list index out of range",
    "statusTrace" : "self = <test_case.TestConduit object at 0x7f436bbcc6d0>\n\n    def test_new_article_from_file(self):\n        # belépés\n        self.test_login()\n        file = open('article_titles.txt', 'r')\n        list = file.read().splitlines() # \\n miatt soronként vágjuk\n        for x in range(5):  # 5 articole létrehozása, az első négy sor lesz egy article adatai...\n            href = self.browser.find_element_by_partial_link_text('New Article')\n            href.click()\n            time.sleep(1)\n            title_input = self.browser.find_element_by_xpath('//input[@placeholder=\"Article Title\"][@type=\"text\"]')\n>           title = list[1+4*x]\nE           IndexError: list index out of range\n\ntest_conduit/test_case.py:177: IndexError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "b059300834c5a9ea",
      "name" : "log",
      "source" : "b059300834c5a9ea.txt",
      "type" : "text/plain",
      "size" : 344
    }, {
      "uid" : "6051a44a5a6f7041",
      "name" : "stderr",
      "source" : "6051a44a5a6f7041.txt",
      "type" : "text/plain",
      "size" : 215
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test_conduit"
  }, {
    "name" : "suite",
    "value" : "test_case"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit"
  }, {
    "name" : "host",
    "value" : "fv-az83-740"
  }, {
    "name" : "thread",
    "value" : "3882-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_conduit.test_case"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "914f010aebaf6515.json",
  "parameterValues" : [ ]
}